# Generated by Django 4.1.4 on 2022-12-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('organisasi', models.CharField(max_length=100)),
                ('kampus', models.TextField()),
                ('agama', models.CharField(max_length=50)),
            ],
        ),
    ]
